### ISSUE TITLE
Fehlende dependency pyxdg

### ISSUE THREAD

**Issue by alexfederlin** [hamarituc/dfs-aip#4]
Bei der installation sowohl auf Gitpod als auch auf Ubuntu Jammy erscheint bei der Ausführung folgender Fehler:

```
(venv) gitpod /workspace/dfs-aip (master) $ basic/aip.py toc fetch
Traceback (most recent call last):
  File "/workspace/dfs-aip/basic/aip.py", line 23, in <module>
    from aip.functions import toc_fetch
  File "/workspace/dfs-aip/basic/aip/functions.py", line 22, in <module>
    from .cache import AipCache
  File "/workspace/dfs-aip/basic/aip/cache.py", line 26, in <module>
    import xdg.BaseDirectory
ModuleNotFoundError: No module named 'xdg.BaseDirectory'
```

Nach installation von pyxdg scheint das Abrufen des toc dann wie erwartet zu laufen.
`pip install pyxdg`

**Comment by hamarituc** [comment]
Ich hatte das ganze eigentlich gegen `xdg` entwickelt, sehe aber nun, dass dieses Paket in `xdg-base-dirs` umbenannt wurde (https://pypi.org/project/xdg/). Ob `pyxdg` kompatibel ist, kann ich nicht sagen. Generell sollten alle Abhängigkeiten aus `requirements.txt` installiert werden.

```
$ pip install -U -r requirements.txt
```

Oder man installiert die Python-Pakete per Distro-Paketmanager, sofern vorhanden.

**Comment by alexfederlin** [comment]
Die requirements.txt hatte ich installiert. 
pyxdg scheint aber tatsächlich nicht der richtige Weg zu sein, denn beim page fetch kommt dann die nächste Fehlermeldung...

Dieser Fork hat die Änderung bzgl xdg-base-dirs implementiert und scheint zu funktionieren: https://github.com/fpletz/dfs-aip

**Comment by hamarituc** [comment]
> Die requirements.txt hatte ich installiert. pyxdg scheint aber tatsächlich nicht der richtige Weg zu sein, denn beim page fetch kommt dann die nächste Fehlermeldung...

So wie ich gerade sehe, kommt das `xdg` doch aus dem `pyxdg`-Paket. D.h. es sollte mit `pyxdg` funktionieren. Kannst du bitte die Fehlermeldung posten?

> Dieser Fork hat die Änderung bzgl xdg-base-dirs implementiert und scheint zu funktionieren: https://github.com/fpletz/dfs-aip

Ui, interessant, wo die Software so überall landet ... und weiterentwickelt wird :smile:

**Comment by alexfederlin** [comment]
Mit den neuesten Änderungen funktioniert alles. Ich nehme an, der Fehler in den ich vorhin noch gelaufen bin wurde durch diesen Commit gefixt: https://github.com/hamarituc/dfs-aip/commit/c00cd6715a8519847cd9756d6092c14850d27a6d

Cooles Projekt - vielen Dank dafür und die schnelle Reaktion 🚀 👍

**Comment by fpletz** [comment]
Danke fürs einbauen einiger meiner Änderungen. :beers: Ich wollte das eigentlich noch aufräumen und einen Pull Request machen aber bin leider nicht dazu gekommen.
